### ISSUE TITLE
mgmt_new_default() always fails (Raspberry Pi)

### ISSUE THREAD

**Issue by shailurie** [IanHarvey/bluepy#73] opened 2015-09-21 17:39 UTC
The Code in the main function which is related to the mgmt function always fails. However it doesnt affect connecting to Bluetooth (as long as the workaround from issue 72 is implemented)

**Comment by IanHarvey** [comment] 2015-09-30 20:01
This was caused by incorrect handling of a return value, which was fixed in 79adf50. It should now be OK (provided that the process has root privilege). Note that bluepy-helper debug is now off by default.

**Closed by IanHarvey** 2015-09-30 20:01 UTC
